package com.hirisun.msg.domain;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;

/**
 * Admin generated by MyEclipse Persistence Tools
 */

public class Admin  implements java.io.Serializable {


    // Fields    

     private String id="0";
     private String userid="";
     private Integer power=0;


    // Constructors

    /** default constructor */
    public Admin() {
    }

    
    /** full constructor */
    public Admin(String userid, Integer power) {
        this.userid = userid;
        this.power = power;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }

    public Integer getPower() {
        return this.power;
    }
    
    public void setPower(Integer power) {
        this.power = power;
    }
   
	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this);
	}
}