package com.hirisun.msg.domain;
/**
 * UserMsg generated by MyEclipse Persistence Tools
 */

public class UserMsg implements java.io.Serializable {

	// Fields

	private String id;
	private String msgid;
	private String userid;
	private Boolean isread;	//true：已读；false：未读

	// Constructors

	/** default constructor */
	public UserMsg() {
	}

	/** full constructor */
	public UserMsg(String msgid, String userid, Boolean isread) {
		this.msgid = msgid;
		this.userid = userid;
		this.isread = isread;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Boolean getIsread() {
		return this.isread;
	}

	public void setIsread(Boolean isread) {
		this.isread = isread;
	}

}