package com.hirisun.msg.domain;
import java.util.Date;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;


/**
 * ShortMessage generated by MyEclipse Persistence Tools
 */

public class ShortMessage  implements java.io.Serializable {


    // Fields    

     private String id;
     private String senduserid;
     private String showsenduserid;
     private String receiveuserid;	//多个接收人用英文逗号”,”分隔，最多可以一次发送给50个人
     private Date sendtime;
     private String content;
     private String parentid;	//null：表示新发的信息；不为null：表示回复的帖子
     private Integer type;		//10：短消息；20：系统消息（全体）21：系统消息（只发给选中的人）
     private Boolean reply;		// true：可回复false：不能回复短消息默认为可回复，系统消息默认为不可恢复，但都可以设置
     private Boolean isread;	//是否已读
     
     final static public int MSG_TYPE_SHORT = 10;
     final static public int MSG_TYPE_SYS_ALL = 20;
     final static public int MSG_TYPE_SYS_ALONE = 21;

    // Constructors

    /** default constructor */
    public ShortMessage() {
    }

    
    /** full constructor */
    public ShortMessage(String senduserid, String showsenduserid, String receiveuserid, Date sendtime, String content, String parentid, Integer type, Boolean reply) {
        this.senduserid = senduserid;
        this.showsenduserid = showsenduserid;
        this.receiveuserid = receiveuserid;
        this.sendtime = sendtime;
        this.content = content;
        this.parentid = parentid;
        this.type = type;
        this.reply = reply;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getSenduserid() {
        return this.senduserid;
    }
    
    public void setSenduserid(String senduserid) {
        this.senduserid = senduserid;
    }

    public String getShowsenduserid() {
        return this.showsenduserid;
    }
    
    public void setShowsenduserid(String showsenduserid) {
        this.showsenduserid = showsenduserid;
    }

    public String getReceiveuserid() {
        return this.receiveuserid;
    }
    
    public void setReceiveuserid(String receiveuserid) {
        this.receiveuserid = receiveuserid;
    }

    public Date getSendtime() {
        return this.sendtime;
    }
    
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getParentid() {
        return this.parentid;
    }
    
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

    public Boolean getReply() {
        return this.reply;
    }
    
    public void setReply(Boolean reply) {
        this.reply = reply;
    }

	public Boolean getIsread() {
		return isread;
	}


	public void setIsread(Boolean isread) {
		this.isread = isread;
	}
	
	@Override
	public String toString() {
		return ReflectionToStringBuilder.toString(this);
	}
}